# Generated by Django 5.0.1 on 2024-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('job_place', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
    ]
