# Generated by Django 5.0.1 on 2024-02-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_coursemodel_gradingsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
