# Generated by Django 5.0.1 on 2024-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_marksmodel_credit_coursemodel_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksmodel',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='marksmodel',
            old_name='student_name',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='courses',
            field=models.ManyToManyField(to='myApp.coursemodel'),
        ),
    ]
