# Generated by Django 5.0.1 on 2024-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_rename_course_name_marksmodel_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingsystem',
            old_name='cgpa',
            new_name='cgp',
        ),
        migrations.AddField(
            model_name='marksmodel',
            name='cgpa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksmodel',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
