# Generated by Django 5.0.1 on 2024-02-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_rename_cgpa_gradingsystem_cgp_marksmodel_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingsystem',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='gradingsystem',
            name='student_name',
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='course_nam',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='student_nam',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='cgp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.marksmodel'),
        ),
    ]
