# Generated by Django 5.0.1 on 2024-02-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_gradingsystem_course_nam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
