# Generated by Django 5.0.1 on 2024-02-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_studentmodel_age_studentmodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksmodel',
            name='cgpa',
        ),
    ]
