# Generated by Django 5.0.1 on 2024-02-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_remove_marksmodel_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='gradingsystem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='gradingsystem',
            name='cgp',
        ),
        migrations.RemoveField(
            model_name='gradingsystem',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marksmodel',
            name='student',
        ),
        migrations.DeleteModel(
            name='courseModel',
        ),
        migrations.DeleteModel(
            name='gradingSystem',
        ),
        migrations.DeleteModel(
            name='marksModel',
        ),
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
